/**
 *
 * $Id$
 */
package minerv1.validation;

import java.util.Date;

import minerv1.Activity;

/**
 * A sample validator interface for {@link minerv1.Event}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventValidator {
	boolean validate();

	boolean validateActivity(Activity value);
	boolean validateDate(Date value);
	boolean validateLifecycleStatus(String value);
}
